# -*- coding: utf-8 -*-
"""Derive every brand asset from the owner-supplied Kissimmee Concrete logo PNG.

Source: brand/logo-source-owner-2026-09-10.png (ChatGPT-generated by the owner,
delivered 2026-09-10, white background, stacked K + KISSIMMEE / CONCRETE +
DRIVEWAYS · PATIOS · WALKWAYS · MORE).

Outputs
  brand/logo-stacked-master.png / logo-stacked-dark-master.png   transparent masters
  brand/icon-k-master.png, wordmark-master.png                    pieces
  brand/logo-horizontal-{light,dark}-master.png                   lockups
  site/static/brand/png|webp/*                                    header/footer renders
  site/static/brand/png/favicon-*.png, site/static/favicon.ico    favicons
  site/static/brand/png/og-default.jpg                            1200x630 social image
"""
from PIL import Image, ImageDraw
import numpy as np
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SITE = os.path.join(HERE, "..", "site", "static")
PNG = os.path.join(SITE, "brand", "png")
WEBP = os.path.join(SITE, "brand", "webp")
os.makedirs(PNG, exist_ok=True)
os.makedirs(WEBP, exist_ok=True)

src = Image.open(os.path.join(HERE, "logo-source-owner-2026-09-10.png")).convert("RGB")
a = np.array(src).astype(int)

# alpha from distance-to-white (the source is on a flat white background)
dist = 255 - np.min(a, axis=2)
alpha = np.clip((dist - 16) * 255 / 56, 0, 255).astype(np.uint8)
rgba = np.dstack([a.astype(np.uint8), alpha])
master = Image.fromarray(rgba, "RGBA")
bbox = Image.fromarray(alpha).point(lambda v: 255 if v > 12 else 0).getbbox()
master = master.crop(bbox)
mw, mh = master.size
print("stacked master", master.size)

# split icon (the K) from the wordmark at the widest horizontal gap in the middle band
al = np.array(master)[:, :, 3]
prof = (al > 12).sum(axis=1)
gap_rows = [y for y in range(int(mh * 0.35), int(mh * 0.75)) if prof[y] == 0]
# take the first contiguous gap band and cut at its middle
bands = []
for y in gap_rows:
    if bands and y == bands[-1][-1] + 1:
        bands[-1].append(y)
    else:
        bands.append([y])
band = max(bands, key=len)
cut = band[len(band) // 2]
print("cut row", cut, "of", mh, "gap band", band[0], band[-1])
icon = master.crop((0, 0, mw, cut)); icon = icon.crop(icon.getbbox())
word = master.crop((0, cut, mw, mh)); word = word.crop(word.getbbox())
print("icon", icon.size, "wordmark", word.size)


def dark_variant(im):
    """Charcoal/black pixels -> warm off-white so the mark reads on dark backgrounds; gold stays."""
    arr = np.array(im).copy()
    rgb = arr[:, :, :3]
    lum = rgb.mean(axis=2)
    sat = rgb.max(axis=2) - rgb.min(axis=2)
    m = (sat < 40) & (lum < 130) & (arr[:, :, 3] > 0)
    arr[m, 0:3] = [244, 241, 234]
    return Image.fromarray(arr, "RGBA")


master_dark = dark_variant(master)
icon_dark = dark_variant(icon)
word_dark = dark_variant(word)


def lockup(ic, wd, gap_ratio=0.10):
    ih = ic.size[1]
    target = int(ih * 0.88)
    s = target / wd.size[1]
    wd2 = wd.resize((int(wd.size[0] * s), target), Image.LANCZOS)
    gap = int(ih * gap_ratio)
    w = ic.size[0] + gap + wd2.size[0]
    out = Image.new("RGBA", (w, ih), (0, 0, 0, 0))
    out.paste(ic, (0, 0), ic)
    out.paste(wd2, (ic.size[0] + gap, (ih - target) // 2), wd2)
    return out


hl = lockup(icon, word)
hd = lockup(icon_dark, word_dark)
print("horizontal", hl.size)

for name, im in [("logo-stacked-master", master), ("logo-stacked-dark-master", master_dark),
                 ("icon-k-master", icon), ("icon-k-dark-master", icon_dark),
                 ("wordmark-master", word), ("wordmark-dark-master", word_dark),
                 ("logo-horizontal-light-master", hl), ("logo-horizontal-dark-master", hd)]:
    im.save(os.path.join(HERE, name + ".png"))


def export(im, name, heights):
    for h in heights:
        s = h / im.size[1]
        r = im.resize((round(im.size[0] * s), h), Image.LANCZOS)
        r.save(os.path.join(PNG, f"{name}-h{h}.png"), optimize=True)
        r.save(os.path.join(WEBP, f"{name}-h{h}.webp"), quality=88, method=6)
        print(name, h, r.size)


export(hl, "logo-horizontal-light", [64, 96, 160, 320])
export(hd, "logo-horizontal-dark", [64, 96, 160, 320])
export(master, "logo-stacked-light", [240, 400])
export(master_dark, "logo-stacked-dark", [240, 400])
export(icon, "icon-k", [64, 128, 256])
export(icon_dark, "icon-k-dark", [64, 128, 256])


def square(im, size, pad=0.06, bg=(0, 0, 0, 0)):
    c = Image.new("RGBA", (size, size), bg)
    inner = int(size * (1 - 2 * pad))
    s = inner / max(im.size)
    r = im.resize((max(1, round(im.size[0] * s)), max(1, round(im.size[1] * s))), Image.LANCZOS)
    c.paste(r, ((size - r.size[0]) // 2, (size - r.size[1]) // 2), r)
    return c


for s in [16, 32, 48, 180, 192, 512]:
    square(icon, s).save(os.path.join(PNG, f"favicon-{s}.png"), optimize=True)
square(icon_dark, 1024, pad=0.16, bg=(24, 24, 24, 255)).save(os.path.join(PNG, "icon-square-dark-1024.png"))
square(icon, 1024, pad=0.16, bg=(255, 255, 255, 255)).save(os.path.join(PNG, "icon-square-light-1024.png"))
ico = [square(icon, s) for s in (16, 32, 48)]
ico[0].save(os.path.join(SITE, "favicon.ico"), format="ICO", sizes=[(16, 16), (32, 32), (48, 48)], append_images=ico[1:])

# Open Graph default: charcoal field, dark lockup, gold rule
og = Image.new("RGB", (1200, 630), (24, 24, 24))
lk = hd.copy(); lk.thumbnail((1000, 260), Image.LANCZOS)
og.paste(lk, ((1200 - lk.size[0]) // 2, 175), lk)
d = ImageDraw.Draw(og)
d.rectangle([0, 606, 1200, 630], fill=(176, 120, 40))
og.save(os.path.join(PNG, "og-default.jpg"), quality=88)
og.save(os.path.join(HERE, "og-default.jpg"), quality=88)

# preview sheet
sheet = Image.new("RGB", (1400, 1250), "white")


def place(im, box, bg):
    x, y, w, h = box
    tile = Image.new("RGB", (w, h), bg)
    c = im.copy(); c.thumbnail((w - 40, h - 40))
    tile.paste(c, ((w - c.size[0]) // 2, (h - c.size[1]) // 2), c)
    sheet.paste(tile, (x, y))


place(hl, (0, 0, 700, 260), (255, 255, 255))
place(hd, (700, 0, 700, 260), (24, 24, 24))
place(master, (0, 270, 700, 520), (244, 241, 234))
place(master_dark, (700, 270, 700, 520), (24, 24, 24))
x = 20
for s in (16, 32, 48, 180, 192):
    ic = Image.open(os.path.join(PNG, f"favicon-{s}.png")).convert("RGBA")
    sheet.paste(ic, (x, 830), ic); x += s + 30
ogp = og.copy(); ogp.thumbnail((700, 370)); sheet.paste(ogp, (700, 830))
sheet.save(os.path.join(HERE, "brand-preview.jpg"), quality=85)
print("done")
