# -*- coding: utf-8 -*-
"""City×service pages: St. Cloud (6), Celebration (5), Poinciana (4)."""
from _data import COST_INDEX_RELEASE
from _helpers import cap, table, svc, city, tool, guide, compare, juris, hoa, faq, cost_rows, cost_range, cs
from _cityservice import cs_page

R = COST_INDEX_RELEASE["label"]


def get_pages():
    p = []

    # ------------------------------------------------------------- St. Cloud
    p.append(cs_page("st-cloud", "concrete-driveways",
        "Concrete Driveways in St. Cloud, FL – City vs. County Permits",
        "Concrete driveways in St. Cloud: 4 in / 3,000 psi on a compacted base, city Building Department vs. Osceola County rules, lakefront Basinger sand, rural long drives over septic-free routes, current cost per sq ft.",
        f"A concrete driveway in St. Cloud runs {cost_range('concrete-driveway-broom')} installed ({R} Cost Index), $2 to $4 more per square foot to remove the old slab. Inside the city, work in the right-of-way needs Public Works and Engineering approval and the Building Department reviews the driveway; outside the line, Osceola County's driveway permit and 24-foot width rule apply. Downtown lots have oaks and Basinger lakefront sand; rural lots have septic drainfields to route around.",
        [
            ("What is different about a St. Cloud driveway", f"<p>Three kinds of lot. Downtown and the East Lake Toho lakefront (1909–1960 homes on brick streets): narrow drives, live oaks planted a century ago, and soil that grades from Smyrna fine sand into Basinger and muck toward the lake, where the water table reaches the surface in June. The 1980s–2000s ranch streets off Nova Road, Canoe Creek Road and Old Hickory Tree Road: standard two-car replacements of 4-inch slabs poured on sand with no base. And the rural lots east and south toward Holopaw: long drives, turnarounds for a boat trailer, and a septic drainfield somewhere in the front yard that a mixer truck and a slab both have to avoid ({guide('septic-drainfield-concrete-driveway')}).</p><p>Our spec is the same as Kissimmee's, 4 inches of 3,000 to 3,500 psi with fiber and #4 edge bars on 4 inches of compacted limerock, or 6 inches with a #4 grid where boats and RVs park, which on St. Cloud's larger lots is often. Lakefront slabs are raised on compacted fill so they sit above the seasonal water, with a swale to the street.</p>"),
            ("Why the city line decides your permit office", f"<p>Inside the City of St. Cloud, the Building Department at 1300 9th Street (407-957-7300) reviews the driveway and anything in the right-of-way needs Public Works and Engineering approval; the city's permit page lists 'driveway reseal for single-family/duplex (existing asphalt only)' as exempt, so a new concrete driveway is not. Outside the city, Osceola County code §22-50.6 requires a county driveway permit for construction or widening and caps width at 24 feet; the Building Office at 1 Courthouse Square (407-742-0200) reviews residential applications in about 3 to 5 days. HB 803's $7,500 exemption (July 1, 2026) does not cover work in the right-of-way. The {tool('permit-finder')} checks the address; {juris('city-of-st-cloud')} and {juris('osceola-county')} quote the sources.</p>"),
        ],
        ("A Canoe Creek Road replacement", f"<p>Two-car driveway, 20 by 26 feet (520 square feet) plus a 12-by-20 boat pad beside the garage, on a 1994 ranch off Canoe Creek Road, county side. Old slab removed ($1,040 to $2,080), new 4-inch drive at $8.50 to $13.50 ($4,400 to $7,000) and the pad at 6 inches with a grid at $11.50 to $17 ($2,760 to $4,080). Three days on site after the county permit, cars back on day 10, the boat trailer after day 28. Ranges from the {R} Cost Index, not a quote.</p>"),
        ("Can I pour a driveway over my drainfield in St. Cloud?", "No. Concrete over a septic drainfield compacts the soil, stops evaporation and can crush the laterals, and Florida's onsite sewage rules keep driveways off drainfields. We pull the county septic record for rural St. Cloud lots, mark the tank and field, and route the driveway or shorten it; where the only route crosses the field, the answer is a relocated drainfield by a septic contractor first."),
        [
            faq("Is a permit needed to replace my St. Cloud driveway?", "Yes. Inside the city, the Building Department and Public Works (for the right-of-way); outside it, the Osceola County driveway permit. Resealing existing asphalt is the only exempt item on the city's list."),
            faq("How wide can a driveway be in St. Cloud?", "Outside the city, 24 feet under county §22-50.6. Inside, the city reviews width with the application; we confirm before quoting a widening."),
            faq("Do lakefront lots need anything special?", "Yes: fill to raise the slab above the summer water table and a swale to carry water away. A slab poured flush on Basinger sand sinks."),
            faq("How long does it take?", "Two to three days on site plus permit time; cars after 7 days, heavy loads after 28."),
        ],
        ["stcloud-permits", "osceola-22-50-6", "osceola-faq", "sda", "hb803"],
        [cs("st-cloud", "paver-driveways"), cs("st-cloud", "concrete-slabs"), compare("concrete-vs-pavers")]))

    p.append(cs_page("st-cloud", "concrete-slabs",
        "Concrete Slabs & Pads in St. Cloud, FL – RV, Boat, Workshop",
        "RV, boat, workshop, shed and generator pads in St. Cloud: 6 in / 4,000 psi with rebar for vehicle loads, raised above the wet-season water table, septic clearances on rural lots, permit rules for the city and Osceola County, costs.",
        f"St. Cloud's larger lots are where we pour most of our RV pads, boat pads and workshop slabs: 6 inches of 4,000 psi with a #4 rebar grid on chairs for vehicles, 4 inches for sheds and equipment, all set 2 to 4 inches above grade on compacted limerock so they stay out of the summer water table. Pads run {cost_range('concrete-slab-pad')} ({R}); a 12-by-40 RV pad lands around $6,500 to $9,500. Sheds are permitted structures; a free-standing pad outside setbacks generally is not.",
        [
            ("Pads on St. Cloud lots", f"<p>The half-acre and acre lots off Old Hickory Tree Road, Nova Road and toward Holopaw were bought for the boat, the camper and the workshop, and the county's soil is the reason pads fail: Smyrna and Myakka fine sand with a water table around 12 inches in summer, EauGallie and Basinger lower still toward the east. A pad flush with the lawn sits in water every June. We build up 2 to 4 inches on compacted base, slope the top ¼ inch per foot, and keep downspouts and sprinklers off it. Workshop slabs for a metal building get a thickened edge and the anchor-bolt layout from the building supplier before we form.</p><p>Access is the other check on a rural lot: a loaded mixer weighs 30-plus tons and will not cross a wet pasture or a culvert rated for a pickup. We look at the route on the site visit and price a pump or a buggy if the truck cannot reach the pad.</p>"),
            ("Permits and septic", f"<p>In the city, sheds, garages and accessory structures need a permit from the Building Department (407-957-7300); the slab is inspected with the structure. In unincorporated Osceola the county publishes shed permit requirements and permits the shed, not the pad; a pad with nothing on it outside setbacks is generally not permitted separately, and HB 803's $7,500 exemption can apply to a stand-alone pad with a written request. A pad that connects to the street as a parking area becomes part of the driveway and needs the driveway permit and the 24-foot rule. Every rural pad is located clear of the septic tank and drainfield from the county record ({guide('septic-drainfield-concrete-driveway')}). Pages: {juris('city-of-st-cloud')}, {juris('osceola-county')}.</p>"),
        ],
        ("A 30-by-40 workshop slab off Nova Road", f"<p>1,200 square feet at 6 inches with a #4 grid and a thickened edge for a pre-engineered metal building, on a county lot with a well and septic. Drainfield located and flagged, subgrade proof-rolled, 6 inches of limerock compacted in two lifts, slab raised 3 inches above grade. About 24 cubic yards of 4,000 psi. Range at 6-inch rates, $11.50 to $17 per square foot: $13,800 to $20,400 for the slab; the building is permitted as an accessory structure. Not a quote.</p>"),
        ("Does an RV pad in St. Cloud need a permit?", "A pad in the back or side yard, outside the setbacks and not connected to the street, generally does not need its own building permit in the county, and HB 803 covers most stand-alone pads under $7,500 with a written request. A pad that connects to the street becomes a driveway extension and needs the county driveway permit and has to fit the 24-foot width rule. Inside the city, confirm with the Building Department; we do before quoting."),
        [
            faq("How thick should a boat pad be?", "Six inches of 4,000 psi with a #4 grid; the trailer's tongue jack and axles are point loads a 4-inch slab will crack under."),
            faq("Can you pour a pad over my drainfield?", "No. We locate it from the county record and keep the pad clear."),
            faq("Will a mixer truck reach my back yard?", "We check on the site visit; if not, a pump truck or a concrete buggy is priced in."),
            faq("How high above grade?", "Two to four inches on compacted base, so the pad stays dry in the wet season."),
        ],
        ["stcloud-permits", "osceola-faq", "hb803", "sda"],
        [cs("st-cloud", "concrete-driveways"), tool("concrete-paver-calculator")]))

    p.append(cs_page("st-cloud", "concrete-repair",
        "Concrete Repair in St. Cloud, FL – Cracks, Sinking, Oak Roots",
        "Concrete repair in St. Cloud: garage-edge steps on 1980s–2000s driveways, oak-root lifting on downtown walks, lakefront slabs sinking into Basinger sand, lift vs. patch vs. replace with costs.",
        f"Most St. Cloud repair calls are one of three: a stepped panel at the garage on a Nova Road or Canoe Creek ranch, a walk lifted by a century-old oak downtown, or a lakefront slab sinking into wet Basinger sand. Routing and sealing cracks or grinding a lip is a minimum-charge visit; replacing a panel runs at new-pour rates ({cost_range('concrete-driveway-broom')}) plus $2 to $4 to remove; lifting is worth it only when the cause is fixed and the panel is sound.",
        [
            ("The three St. Cloud failure patterns", f"<p><strong>Garage-edge step.</strong> Roof runoff and a downspout aimed at the slab edge wash fine sand out from under the panel; the panel drops an inch and cracks. Fix the water first, then lift or replace the panel. <strong>Oak lift.</strong> Downtown's 1910s–1950s streets have live oaks whose roots lift walk and driveway panels 2 to 3 inches; grinding buys a year, a root barrier and a replaced panel buys a decade ({guide('tree-roots-driveways-central-florida')}). <strong>Lakefront settlement.</strong> Slabs poured flush on Basinger sand or muck along East Lake Toho and Alligator Lake sink unevenly as the water table cycles; the fix is a raised, drained replacement, not a patch.</p>"),
            ("When a repair is not worth it", f"<p>A 1985 driveway with one stepped panel and hairline cracks in the others is on one clock; we price the panel and the whole drive so the choice is yours with numbers. Polyurethane lifting is the right call for a sound, newer slab with a small void after the water problem is solved; it is the wrong call for a cracked apron panel that carries the load. The decision tree with costs is {compare('resurface-vs-replace')}. Repairs in the same footprint need no permit; replacing an apron in the right-of-way inside the city needs Public Works approval, and in the county the driveway permit ({juris('city-of-st-cloud')}, {juris('osceola-county')}).</p>"),
        ],
        ("A garage-edge panel on Old Hickory Tree Road", f"<p>One 10-by-12 panel stepped 1½ inches at the garage door on a 1998 driveway, rest of the drive sound. Downspout extended 6 feet past the slab, panel saw-cut and removed ($240 to $480), base rebuilt and compacted, new 4-inch panel doweled to the neighbors and poured at $8.50 to $13.50 ($1,020 to $1,620), expansion joint at the garage. One day plus cure. Ranges from the {R} index.</p>"),
        ("Why is my driveway sinking near the garage in St. Cloud?", "Water. The roof edge or a downspout dumps every storm at the slab edge, the fine sand under it washes out, and the panel drops. The county's Smyrna and Myakka sands lose support fast once water moves through them. Extend the downspout past the slab, then lift or replace the panel; a repair without fixing the water comes back."),
        [
            faq("Can you just lift the sunken panel?", "If it is intact and the water source is fixed, yes, through a lifting contractor. If it is cracked through or it is the apron, replacement is the better spend."),
            faq("Will the new panel match?", "It will be lighter for about a year. A straight joint at the seam makes it read as intentional."),
            faq("Do repairs need a permit?", "Not in the same footprint. Aprons in the right-of-way inside the city need Public Works approval; in the county, the driveway permit."),
            faq("Can oak roots be cut?", "Small ones at the slab edge, with a root barrier installed. Cutting large structural roots endangers the tree; we reroute or bridge instead."),
        ],
        ["stcloud-permits", "osceola-22-50-6", "sda"],
        [cs("st-cloud", "concrete-driveways"), guide("why-concrete-cracks-osceola")]))

    p.append(cs_page("st-cloud", "paver-driveways",
        "Paver Driveways in St. Cloud, FL – Public Works, Base, Cost",
        "Paver driveways in St. Cloud: the city refers driveway pavers to Public Works (no building permit), Osceola County rules outside the line, 6-inch base on flatwoods sand, builder-driveway rebuilds in Narcoossee, cost per sq ft.",
        f"A paver driveway in St. Cloud runs {cost_range('paver-driveway-concrete')} installed ({R} Cost Index) on a 6-inch compacted limerock base with 80 mm pavers and a concrete apron at the street. Inside the city, driveway pavers are referred to Public Works rather than the Building Department; outside the line, Osceola's driveway permit and 24-foot rule apply. Half of our St. Cloud paver work is rebuilding builder driveways in the Narcoossee-corridor communities that settled on thin base.",
        [
            ("Builder pavers in Narcoossee, Sunbridge and Anthem Park", f"<p>The 2015–2026 communities along Narcoossee Road were built with paver driveways set on 2 to 4 inches of base by production crews working through the rainy season, and by year five many have a dip at the garage, a rolled outside course where edge restraint was skipped, and joints that lost their sand to ants. The fix is the lift-and-relay: pull the pavers, rebuild the base to 6 inches, reset the same units, add restraint on the base, re-sand with polymeric ({svc('paver-repair')}). Where the whole field has moved we rebuild from the subgrade. First sealing at 60 to 90 days is the other job the builders leave undone ({cs('st-cloud', 'paver-sealing')}).</p>"),
            ("Permits and the apron", f"<p>The city's Permit Information page lists 'pavers for driveways/sidewalks (refer to Public Works)' among items that do not need a building permit, and any work in the right-of-way needs Public Works and Engineering approval; the apron at the street is where those two meet, and most jurisdictions want it poured in concrete rather than pavers. Outside the city, Osceola County's driveway permit under §22-50.6 covers a paver driveway and the 24-foot width limit applies. HOA approval in the newer communities comes first; the {tool('hoa-packet-checklist')} lists the attachments. Pages: {juris('city-of-st-cloud')}, {juris('osceola-county')}, {tool('permit-finder')}.</p>"),
        ],
        ("A rebuilt two-car driveway in Anthem Park", f"<p>480 square feet of builder pavers dipped 2 inches at the garage and rolled along the lawn edge, 2018 installation. Pavers lifted and stacked, 2 inches of failed base removed and replaced with 6 inches compacted in lifts, spiked aluminum restraint on the base, same pavers reset with 12 cut replacements from a matched lot, polymeric sand, seal at 60 days. Full lift-and-relay priced at repair rates, {cost_range('paver-repair')}: $4,300 to $7,700, versus $6,700 to $10,600 for a new field. Ranges from the {R} index.</p>"),
        ("Do driveway pavers need a permit in St. Cloud?", "Not a building permit inside the city: the city's own list refers driveway and sidewalk pavers to Public Works, and work in the right-of-way (the apron) needs Public Works and Engineering approval. Outside the city line, a paver driveway is a driveway under Osceola County §22-50.6: county driveway permit, 24-foot maximum width. Your HOA's approval comes before either."),
        [
            faq("Why did my builder's pavers sink?", "Thin base placed on wet sand during the rainy season, and no edge restraint on the base. Rebuilding the base under the same pavers fixes it."),
            faq("Concrete apron or pavers to the street?", "Concrete in the right-of-way in most cases; pavers stop at a soldier course at the apron. Public Works reviews the connection inside the city."),
            faq("How long does a paver driveway take in St. Cloud?", "Three to five working days for a two-car drive including removal; a lift-and-relay of a builder drive is two to three."),
            faq("Which pavers match my community?", "We identify the builder's line and source the current equivalent from Belgard, Tremron or Oldcastle."),
        ],
        ["stcloud-permits", "osceola-22-50-6", "icpi"],
        [cs("st-cloud", "concrete-driveways"), cs("st-cloud", "paver-sealing"), guide("paver-base-flatwoods-vs-ridge")]))

    p.append(cs_page("st-cloud", "paver-pool-decks",
        "Paver Pool Decks in St. Cloud, FL – Overlays, Travertine, Permit",
        "Paver and travertine pool decks in St. Cloud: overlays on 2000s decks, lakefront homes, the city's deck permit rule, lanai drain channels, which surface stays coolest, cost for a 600 sq ft deck.",
        f"A paver overlay on a sound St. Cloud pool deck runs {cost_range('paver-pool-deck')} ({R}), a travertine deck {cost_range('travertine-pool-deck')}; a 600-square-foot deck is $9,000 to $14,400 as an overlay. The City of St. Cloud lists decks among permit-required projects, so an overlay inside the city is confirmed with the Building Department before we schedule; the county treats a deck outside setbacks as flatwork. Four to seven days; the pool stays full.",
        [
            ("Pool decks on St. Cloud's lakefront and in its subdivisions", f"<p>Lakefront homes on East Lake Toho and the canals off Lakeshore Boulevard tend to want travertine or marble for the look and the cooler surface, and their decks sit on wetter ground where a full rebuild on compacted fill beats an overlay. The 2000s subdivisions (Anthem Park, Canoe Creek Estates, the Nova Road communities) have 20-year-old textured concrete decks inside screen cages that are sound but tired: those get a 1-inch remodel paver overlay with new bullnose coping and a drain channel at the screen line. Newer Narcoossee homes with builder paver decks need sealing and, occasionally, a lift-and-relay where pool backfill settled. Heat and slip: light travertine and marble measure coolest in published comparisons; sealers get an anti-slip additive ({guide('surface-temperature-pool-decks')}).</p>"),
            ("Permits and the screen cage", f"<p>Inside the city, patios and decks are on the permit list, so we confirm the overlay's status with the Building Department (407-957-7300) before scheduling; a deck tied to the pool's bond beam or to the screen enclosure footer is reviewed. Outside the city, unincorporated Osceola treats a deck outside setbacks as flatwork; a screen enclosure replacement is its own permitted structure with footers that go in before the deck. HOA review applies in the subdivisions. Pages: {juris('city-of-st-cloud')}, {juris('osceola-county')}, {tool('permit-finder')}.</p>"),
        ],
        ("A lakefront travertine rebuild", f"<p>640-square-foot deck around a 15-by-30 pool on a canal lot, old concrete deck cracked and heaved 1 inch at the coping. Deck removed, pool backfill compacted, 4 inches of base, tumbled ivory travertine sand-set with mortar-set bullnose coping and a drain channel at the cage line. At {cost_range('travertine-pool-deck')}: $12,800 to $23,000 plus coping ($28 to $55 per linear foot) and removal. Seven days; pool full throughout. Ranges from the {R} index.</p>"),
        ("Do I need a permit to put pavers over my pool deck in St. Cloud?", "Inside the city, decks are on the permit list, so we confirm with the Building Department whether your overlay is treated as maintenance or as a deck; a deck tied to the bond beam or the cage footer is reviewed. In unincorporated Osceola an overlay on a deck outside the setbacks is flatwork. Either way the pool stays full and the HOA, if any, reviews the visible change first."),
        [
            faq("Overlay or rebuild?", "Overlay if the deck is sound (no heaving, no hollows) and the added inch works at the doors and coping; rebuild on lakefront or settled decks."),
            faq("Which surface stays coolest?", "Light travertine and marble in published measurements; we plan to measure decks here in July."),
            faq("How long is the pool unusable?", "It isn't; swimmers stay out only while coping mortar cures, about 48 hours."),
            faq("Does the drain go to the pool?", "No; to a channel at the screen line or away from the pool to the yard."),
        ],
        ["stcloud-permits", "icpi"],
        [cs("st-cloud", "paver-sealing"), compare("travertine-vs-concrete-pavers"), compare("cool-deck-vs-pavers")]))

    p.append(cs_page("st-cloud", "paver-sealing",
        "Paver Sealing in St. Cloud, FL – First Seal, Re-Seal, Rust",
        "Paver sealing and re-sanding in St. Cloud: first seal on builder driveways in Narcoossee and Sunbridge, re-seal cycles for driveways and pool decks, well-water rust stains, efflorescence, cost per sq ft.",
        f"Cleaning, polymeric re-sanding and sealing runs {cost_range('paver-sealing')} in St. Cloud ({R} Cost Index): about $850 to $1,550 for a two-car driveway, $1,050 to $1,950 for a 600-square-foot pool deck. Builder driveways in the Narcoossee corridor are due for a first seal at 60 to 90 days and almost never get it; older drives and pool decks are on a three- to four-year cycle. Well irrigation east of the city utility area leaves rust that is treated before sealing, never under it.",
        [
            ("Sealing the builder's pavers", f"<p>Weslyn Park, Del Webb Sunbridge, Nova Grove and Bridgewalk homes come with paver driveways that were never sealed and whose joints were filled with regular sand. By the second summer the joints have ants and weeds and the surface has the white efflorescence haze every new concrete paver sheds during its first rainy season. The first seal, done right, is: wait for the efflorescence to finish (60 to 90 days), clean it with an efflorescence cleaner, re-sand with polymeric sand installed dry and vibrated in, then two thin coats of sealer on a dry deck ({svc('paver-sealing', 'full process')}). On rental-heavy and pool-side surfaces we add an anti-slip additive.</p>"),
            ("Rust, wells and the sealer choice", f"<p>East and south of the city utility area most homes irrigate from wells, and the iron in that water oxidizes on pavers as orange streaks along the sprinkler arc within weeks. Sealing over rust locks it in; we remove it with an iron-specific cleaner first and tell you the stain will return unless the heads are adjusted or an iron filter goes on the line ({guide('rust-stains-irrigation-well-water')}). Sealer type: a penetrating, breathable product on travertine and on pavers that have haze problems; a film-forming acrylic where the wet look is wanted and the deck dries fully. {compare('sealer-types')} explains the chemistry. No permit and, for a like-for-like clear seal, usually no HOA review.</p>"),
        ],
        ("First seal on a Weslyn Park driveway", f"<p>460 square feet of builder pavers, 14 months old, efflorescence gone, ant mounds in the joints, sprinkler rust along one edge. Rust removed, efflorescence cleaner, pressure wash at 2,800 psi, two dry days, polymeric re-sand, two coats of penetrating sealer. At {cost_range('paver-sealing')}: $805 to $1,495. One dry morning for the sand, one for the sealer. Ranges from the {R} index.</p>"),
        ("Should I seal the pavers the builder installed?", "Yes, once the efflorescence has run its course, which is 60 to 90 days after installation. Sealing before that traps the white haze under the film. The builder's regular joint sand should be replaced with polymeric at the same visit; that is what stops the ants and weeds that show up in the first summer."),
        [
            faq("How often do pavers need sealing in St. Cloud?", "Driveways every three to four years, pool decks every two to three; travertine every three to four with a penetrating sealer."),
            faq("Why are there orange streaks on my pavers?", "Iron in well water from the sprinklers. It is removed with an iron-specific cleaner, and it comes back unless the heads are adjusted or the water is filtered."),
            faq("Can you seal in the rainy season?", "On a morning with a dry 24-hour forecast; we reschedule rather than seal ahead of a storm."),
            faq("Wet look or natural?", "Your choice, unless the HOA specifies matte. Wet look needs more frequent re-coating."),
        ],
        ["icpi"],
        [cs("st-cloud", "paver-driveways"), cs("st-cloud", "paver-pool-decks"), guide("polymeric-sand-guide")]))

    # ------------------------------------------------------------- Celebration
    p.append(cs_page("celebration", "paver-driveways",
        "Paver Driveways in Celebration, FL – ARC, Alleys, Approved Blends",
        "Paver driveways and alley aprons in Celebration: CROA Architectural Review Committee (third Monday), village palettes, matching 1996–2006 builder blends, Osceola County permit and 24-ft rule, costs.",
        f"Paver driveway work in Celebration runs {cost_range('paver-driveway-concrete')} for standard lines and {cost_range('paver-driveway-premium')} for premium blends ({R} Cost Index), and it starts with the CROA's Architectural Review Committee, which meets on the third Monday of each month and reviews material, color, pattern and edge detail. Most 1996–2006 homes have rear alley garages with short paver aprons; the county driveway permit applies to any new or widened drive (24-foot maximum).",
        [
            ("Alley aprons and front drives", f"<p>Celebration Village, Lake Evalyn and West Village were built with alley-loaded garages and 15- to 25-foot paver aprons between the alley and the door; thirty years on, the builder's pavers have settled where the alley's stormwater runs across them and the outside course has rolled. North, South and East Village add front-loaded lots with longer drives and the community's brick-and-paver front walks. A rebuild here is a lift-and-relay on a 6-inch base with edge restraint, or a full replacement in the village's approved blend; matching the original tumbled clay-look units is the hard part, and the manufacturers' current equivalents are close but not identical, so we sample first and borrow original units for the visible seam where needed ({svc('paver-repair', 'matching discontinued pavers')}).</p>"),
            ("ARC first, county second", f"<p>The ARC application needs a site plan or survey markup, product name, color, pattern, edge detail and a sample; each village has its own accents and joint-sand color has been a reason for rejection. Complete packets submitted before the agenda deadline are decided at the third-Monday meeting; Town Hall at 851 Celebration Avenue (407-566-1200 ext. 2206) has the current Design Guidelines for owners. Then the county: unincorporated Osceola requires a driveway permit for construction or widening under §22-50.6 with the 24-foot limit, at the Building Office, 1 Courthouse Square (407-742-0200). The alleys are private streets maintained by the community, so the ARC approval doubles as the access approval. Pages: {hoa('celebration')}, {juris('osceola-county')}, {tool('hoa-packet-checklist')}.</p>"),
        ],
        ("A Lake Evalyn alley apron", f"<p>18-by-22-foot apron (396 square feet) of 1998 tumbled pavers, dipped 1½ inches where the alley drains across it, outside course rolled. Lifted, base rebuilt to 6 inches with the alley edge regraded to a swale, restraint set, original units reset with 30 replacements from a matched lot placed at the garage line, polymeric sand, seal at 60 days. At repair rates ({cost_range('paver-repair')}): $3,560 to $6,340; a full replacement in a premium blend would run $7,900 to $13,500. ARC approval took one meeting cycle. Ranges from the {R} index.</p>"),
        ("Can I widen my driveway in Celebration?", "Only with ARC approval and within the county's 24-foot limit. Front-loaded lots in North and South Village have little room before the setback and the street trees; alley lots are limited by the garage line. Most widening requests here end up as a paver parking strip beside the apron, which the committee reviews the same way as the driveway."),
        [
            faq("Who approves a paver driveway in Celebration?", "The CROA Architectural Review Committee, monthly on the third Monday, then the Osceola County driveway permit for a new or widened drive."),
            faq("Can you match the original pavers?", "Closely, from the manufacturers' current equivalents; we sample first and use original units at the visible seams."),
            faq("Is the alley mine to fix?", "The apron on your lot is yours; the alley itself is maintained by the community. Regrading the alley edge needs the ARC's sign-off."),
            faq("How long does the whole process take?", "Four to six weeks from packet to work, driven by the meeting cycle; the work itself is three to five days."),
        ],
        ["celebration", "osceola-22-50-6", "osceola-faq", "icpi"],
        [cs("celebration", "paver-walkways-steps"), cs("celebration", "paver-sealing"), tool("hoa-packet-checklist")]))

    p.append(cs_page("celebration", "paver-pool-decks",
        "Paver Pool Decks in Celebration, FL – Travertine, ARC, Overlays",
        "Travertine and paver pool decks in Celebration: overlays on 2000s decks inside screened lanais, ARC review of visible changes, Osceola County flatwork rules, lanai drains tied to community stormwater, costs.",
        f"A paver overlay on a sound Celebration pool deck runs {cost_range('paver-pool-deck')} and a travertine deck {cost_range('travertine-pool-deck')} ({R} Cost Index). Decks inside a screened lanai and not visible from the street or a neighbor may still fall under CROA review because the Design Guidelines cover exterior materials; we confirm with Town Hall. Unincorporated Osceola treats an overlay outside setbacks as flatwork. Four to seven days, pool full.",
        [
            ("Celebration's 1999 to 2006 concrete decks are ready for stone", f"<p>The pool homes in North Village, South Village, East Village and Artisan Park mostly have textured concrete decks poured with the pool twenty years ago, sound but faded, inside screened lanais. Those take a 1-inch remodel paver or travertine overlay with new bullnose coping and a channel drain at the screen line; the community's lanai drains tie into its stormwater system, and we keep that connection. Owners here ask for travertine and, on the contemporary Island Village homes, large-format porcelain, both of which stay cooler than gray concrete pavers in published measurements ({compare('travertine-vs-concrete-pavers')}). Sealers on the deck get an anti-slip additive; travertine gets a penetrating sealer only.</p>"),
            ("Review and permits", f"<p>Whether a lanai deck needs ARC review depends on visibility and on the Design Guidelines' material rules; Town Hall (407-566-1200 ext. 2206) confirms, and a complete packet is decided at the monthly meeting. For the county, an overlay on an existing deck outside setbacks is flatwork; a deck tied to the pool bond beam or the screen footer is confirmed with the Building Office (407-742-0200) first, and a cage replacement is its own permitted structure. Pages: {hoa('celebration')}, {juris('osceola-county')}, {tool('hoa-packet-checklist')}.</p>"),
        ],
        ("A South Village travertine overlay", f"<p>560-square-foot deck around a 12-by-26 pool inside a screened lanai, 2001 textured concrete, sound. Cleaned and leveled, ½-inch travertine tile thin-set over the slab, new tumbled bullnose coping, channel drain at the screen line tied to the existing lanai drain. At {cost_range('travertine-pool-deck')}: $11,200 to $20,200 plus coping. Five days; ARC packet decided at the next third-Monday meeting. Ranges from the {R} index.</p>"),
        ("Does a pool deck inside my lanai need ARC approval in Celebration?", "Sometimes. The CROA Design Guidelines cover exterior materials, and whether a screened lanai floor is treated as visible depends on the lot and the village; Town Hall gives a definite answer for your address in a phone call. We ask before we quote, and if review is needed the packet is a sample, a photo of the lanai and a note on drainage, decided at the monthly meeting."),
        [
            faq("Overlay or full rebuild?", "Overlay on a sound deck; rebuild if the deck heaves, sounds hollow or has settled at the coping."),
            faq("Travertine or porcelain?", "Travertine for the traditional villages, large-format porcelain on contemporary Island Village homes; both stay cooler than gray pavers."),
            faq("Where does the lanai drain go?", "To the community stormwater connection your lanai already has; we keep it."),
            faq("How long does it take?", "Four to seven days plus the ARC cycle if review is required."),
        ],
        ["celebration", "osceola-faq", "icpi"],
        [cs("celebration", "paver-sealing"), svc("paver-travertine"), svc("paver-marble-porcelain")]))

    p.append(cs_page("celebration", "paver-sealing",
        "Paver Sealing in Celebration, FL – Matte vs. Wet Look, ARC",
        "Paver sealing, cleaning and re-sanding in Celebration: keeping the village palette, matte vs. wet-look under ARC review, efflorescence on new Island Village pavers, oak-shade mold, cost per sq ft.",
        f"Sealing in Celebration runs {cost_range('paver-sealing')} including cleaning and polymeric re-sanding ({R} Cost Index). A like-for-like clear seal is maintenance; switching a matte driveway to a wet-look finish is a change the ARC may want to see, so we ask Town Hall before switching products. Island Village's new pavers need their first seal after efflorescence clears; the older villages' shaded walks and aprons need mold removal before sealing.",
        [
            ("Sealing under the oaks", f"<p>Celebration's street trees and the older villages' canopy keep front walks and alley aprons shaded and damp, which grows black and green film on unsealed pavers every summer. The routine: surface cleaner on a pressure washer at 2,500 to 3,000 psi with a wide tip (narrow tips etch the tumbled finish), a mold treatment, two dry days, polymeric re-sand, then a breathable sealer that lets the deck dry through. Wet-look acrylics on a shaded apron haze white within a year because the pavers never fully dry; we recommend the penetrating product there and say so ({compare('sealer-types')}).</p>"),
            ("Island Village and first seals", f"<p>The 2020–2026 Island Village homes come with unsealed builder pavers in the village's approved blend and regular joint sand. The first seal waits 60 to 90 days for efflorescence, then cleans it, re-sands with polymeric and seals matte, which is what the streetscape reads as. ARC review: a clear seal in the existing finish is maintenance; a finish change is reviewed. Town Hall (407-566-1200 ext. 2206) answers by phone. {hoa('celebration')}; process: {svc('paver-sealing')}.</p>"),
        ],
        ("A North Village front walk and apron", f"<p>220 square feet of walk and apron in tumbled pavers under two street oaks, black film, joints half empty. Mold treatment, wash, two dry days, polymeric re-sand, two coats of penetrating sealer. At {cost_range('paver-sealing')} with a small-job minimum: $450 to $720. Half a day of work over two mornings. Ranges from the {R} index.</p>"),
        ("Do I need ARC approval to seal my pavers in Celebration?", "Not for a clear seal that keeps the existing finish; that is maintenance. Changing the look, from matte to wet-look or adding a tint, is a material change under the Design Guidelines and Town Hall may ask for a sample. We check with them before we switch products on a Celebration lot."),
        [
            faq("Why do my sealed pavers look white?", "A film-forming sealer applied over moisture on a shaded apron. Strip and re-seal with a penetrating product."),
            faq("How often in Celebration?", "Shaded walks and aprons every two to three years; sunny driveways every three to four."),
            faq("Do you treat mold?", "Yes, before sealing; sealing over it seals it in."),
            faq("Can you match the village finish?", "Matte is the streetscape default and what a penetrating sealer gives."),
        ],
        ["celebration", "icpi"],
        [cs("celebration", "paver-driveways"), cs("celebration", "paver-walkways-steps"), guide("polymeric-sand-guide")]))

    p.append(cs_page("celebration", "paver-walkways-steps",
        "Paver Walkways & Steps in Celebration, FL – Streetscape Palette",
        "Paver front walks, side paths and entry steps in Celebration: matching the village's brick-and-paver streetscape, ARC review, oak-root damage, 4-in base and edge restraint, costs per sq ft and per step.",
        f"A paver walkway in Celebration runs {cost_range('paver-walkway')} ({R} Cost Index); entry steps are rebuilt per riser. The front walk is part of the streetscape the Design Guidelines protect, so material, pattern and border go through the Architectural Review Committee (third Monday). The work is mostly replacing 1996–2006 walks lifted by the street oaks and rebuilding stoops whose risers have settled unevenly.",
        [
            ("Walks in the village pattern", f"<p>Celebration's front walks were laid in a brick-look running bond with a border that varies by village, from the sidewalk to a stoop of two or three risers. Thirty years of oak roots and settled base have lifted panels and opened joints; the repair is a lift-and-relay on a compacted 4-inch base with edge restraint set on the base on both sides, the original units reset, replacements from a matched lot at the ends. Where a root has lifted a section 2 inches or more we install a root barrier and reset over it rather than cut the root ({guide('tree-roots-driveways-central-florida')}). Steps: block risers on a footing, paver treads with a nosing, riser heights equalized within ¼ inch, which is usually why the old stoop felt wrong.</p>"),
            ("Review and permits", f"<p>The ARC packet for a walk is a sketch on the survey, product, pattern, border and a sample; Town Hall (407-566-1200 ext. 2206) has the village guidelines. A private walk on the lot needs no county permit; a section that crosses the public sidewalk strip is the county's right-of-way under LDC 4.12.2 and is confirmed with the Building Office (407-742-0200). Pages: {hoa('celebration')}, {juris('osceola-county')}, {tool('hoa-packet-checklist')}.</p>"),
        ],
        ("A West Village walk and stoop", f"<p>42-foot front walk, 4 feet wide (168 square feet) in tumbled clay-look pavers lifted at one oak, plus a three-riser stoop with a 1½-inch difference between risers. Walk lifted and relaid over a root barrier on a rebuilt base ({cost_range('paver-repair')}: $1,510 to $2,690); stoop rebuilt with block risers and paver treads ($250 to $450 per step: $750 to $1,350). Two days after ARC approval. Ranges from the {R} index.</p>"),
        ("Can I change my front walk's pattern in Celebration?", "With ARC approval, within the village's palette. The Design Guidelines treat the front walk as part of the streetscape, so a change in material, pattern or border is reviewed at the monthly meeting with a sample. A like-for-like repair in the same units is maintenance and moves faster."),
        [
            faq("Who approves a walkway change?", "The CROA Architectural Review Committee; Town Hall has the village-specific guidelines."),
            faq("Can you fix the lifted section without redoing the whole walk?", "Yes; a lift-and-relay over a root barrier on the affected run, with matched units at the seam."),
            faq("Is a permit needed?", "Not for a private walk on the lot; the strip across the public sidewalk is county right-of-way and is confirmed first."),
            faq("How much is a stoop rebuild?", "About $250 to $450 per riser plus the landing, in paver treads; travertine or porcelain treads add material."),
        ],
        ["celebration", "osceola-faq"],
        [cs("celebration", "paver-driveways"), cs("celebration", "concrete-repair"), svc("paver-outdoor-lighting")]))

    p.append(cs_page("celebration", "concrete-repair",
        "Concrete Repair in Celebration, FL – Garage Slabs, Walks, Aprons",
        "Concrete repair in Celebration: garage slab edges at alley aprons, public sidewalk panels lifted by street oaks, lanai slab cracks before a paver overlay, ARC notes for visible repairs, costs.",
        f"Concrete repair in Celebration is mostly three things: the garage slab edge where the alley apron meets it, sidewalk and walk panels lifted by the street oaks, and cracked lanai slabs being prepared for a paver or travertine overlay. Crack routing and grinding is a minimum-charge visit; a replaced panel runs at new-pour rates ({cost_range('concrete-driveway-broom')}) plus removal. Visible repairs on the street side are noted to the ARC; the county needs no permit for same-footprint repair.",
        [
            ("Where Celebration concrete fails", f"<p>The 1996–2006 homes have concrete garage slabs meeting paver aprons at the alley; the slab edge spalls and the last foot cracks where the apron settled and the expansion joint was never installed. Public sidewalk panels along the tree-lined streets lift 1 to 2 inches at live oaks; those panels are in the community's and county's domain and we repair them under the right approval. Lanai slabs poured with the pool in 2000 have shrinkage cracks that are fine to overlay and, occasionally, a heaved corner at the coping that is not ({compare('resurface-vs-replace')}). Well-water rust is rare here because Celebration is on utility water; the stains we see are tannin from the oaks, treated differently ({guide('rust-stains-irrigation-well-water')}).</p>"),
            ("Approvals", f"<p>Same-footprint repair needs no county permit. A replaced sidewalk panel in the public strip is county right-of-way and community streetscape, so both the Building Office (407-742-0200) and Town Hall (407-566-1200 ext. 2206) are told; a garage-edge repair behind the house is maintenance. The new concrete will be lighter for a year, which is why we note visible repairs to the ARC. Pages: {hoa('celebration')}, {juris('osceola-county')}.</p>"),
        ],
        ("A garage-edge repair at an alley apron", f"<p>The last 3 feet of a 20-foot-wide garage slab spalled and cracked where the apron settled; apron relaid on a rebuilt base ({cs('celebration', 'paver-driveways', 'see the alley apron example')}), slab edge saw-cut and removed (60 square feet, $120 to $240), new 4-inch section doweled to the slab and poured at $8.50 to $13.50 ($510 to $810), expansion joint installed at the apron. One day. Ranges from the {R} index.</p>"),
        ("Who fixes the lifted public sidewalk in front of my Celebration house?", "It is in the county's right-of-way and the community's streetscape, so the answer depends on what lifted it and who is responsible for the tree; Town Hall is the first call. When the owner takes it on, we repair the panel under the county's right-of-way rules and the ARC's streetscape standard, with a root barrier so it does not lift again."),
        [
            faq("Do repairs need ARC approval?", "Visible ones are noted to the committee because new concrete is lighter for a year; maintenance behind the house is not reviewed."),
            faq("Can you overlay a cracked lanai slab?", "Shrinkage cracks, yes, routed and filled first. A heaved corner at the coping is repaired before any overlay."),
            faq("What causes the garage-edge cracks?", "The alley apron settling with no expansion joint between apron and slab; the fix is both."),
            faq("Is a permit needed?", "Not for same-footprint repair; sidewalk panels in the public strip are confirmed with the county."),
        ],
        ["celebration", "osceola-faq"],
        [cs("celebration", "paver-driveways"), cs("celebration", "paver-walkways-steps"), guide("why-concrete-cracks-osceola")]))

    # ------------------------------------------------------------- Poinciana
    p.append(cs_page("poinciana", "concrete-driveways",
        "Concrete Driveways in Poinciana, FL – DCB Approval, Two Counties",
        "Concrete driveway replacement in Poinciana: APV Design Control Board approval first (9.1.1 materials, 30-day deemed denial), Osceola or Polk permit by village, 1970s–90s slab tear-outs, costs for a two-car drive.",
        f"Replacing a Poinciana driveway runs {cost_range('concrete-driveway-broom')} plus $2 to $4 per square foot for removal ({R} Cost Index), and it starts with an APV Design Control Board application: no driveway may be started without prior written approval, concrete, asphalt and brick pavers are the accepted materials, and an application not acted on within 30 days is deemed disapproved. Then the permit from whichever county your village is in.",
        [
            ("In Villages 1 through 6 the original slabs are done", f"<p>The 1972–1990 villages off Marigold Avenue, Pleasant Hill Road and Cypress Parkway have 4-inch driveways poured on graded sand with no base, and after forty wet seasons on Smyrna and Myakka fine sand they have cracked into panels with a step at the garage and a broken apron corner. Repairing one panel buys a few years ({cs('poinciana', 'concrete-repair')}); most owners replace. Our replacement spec: 4 inches of 3,000 to 3,500 psi with fiber and #4 edge bars on 4 inches of compacted limerock, sloped to the street, downspouts extended past the slab. The western villages climb onto Candler sand at the edge of the Polk ridge, where the base is wetted before compaction ({guide('paver-base-flatwoods-vs-ridge')}).</p>"),
            ("DCB, then the county", f"<p>The DCB application goes to APV at 401 Walnut Street (863-427-0900) with a site plan, material and color; a like-for-like concrete replacement is routine but still required, and silence for 30 days is a denial, not an approval. Width follows the village's existing driveway requirements (Criteria 9.1.1). Then the permit: Osceola villages use the county driveway permit (§22-50.6, 24-foot maximum, Building Office 407-742-0200); Polk villages use the Polk Building Division (863-534-6080) for portions in the right-of-way or within setbacks. The {tool('permit-finder')} shows the county; pages: {hoa('poinciana-apv')}, {juris('osceola-county')}, {juris('polk-county')}.</p>"),
        ],
        ("A Village 2 two-car replacement", f"<p>18-by-22-foot drive (396 square feet), 1981 slab cracked into four panels with a 2-inch step at the garage, Osceola side. DCB approval in two weeks, county driveway permit, removal ($790 to $1,580), new 4-inch drive at $8.50 to $13.50 ($3,370 to $5,350), apron matched to the county detail. Three days; cars after 7. Ranges from the {R} index.</p>"),
        ("Do I need APV approval to replace my Poinciana driveway with the same concrete?", "Yes. The DCB criteria require prior written approval before any driveway or paved area is commenced, without exception for like-for-like work. A same-material replacement is usually approved quickly, but starting without the letter is a violation the association can require you to undo. Send the application first; the county permit follows."),
        [
            faq("Which county issues my permit?", "Depends on the village. The permit finder checks the address; APV's office can also tell you."),
            faq("Can I widen the driveway?", "Within the village's existing width requirement under Criteria 9.1.1 and, on the Osceola side, the county's 24-foot limit. The DCB decides."),
            faq("Concrete or pavers?", "Concrete is the DCB's default and the cheaper option; brick pavers are also an accepted material with approval."),
            faq("How long does DCB approval take?", "Typically two to four weeks; 30 days without a decision counts as a denial, so we follow up."),
        ],
        ["apv", "osceola-22-50-6", "polk-faq", "sda"],
        [cs("poinciana", "paver-driveways"), cs("poinciana", "concrete-repair"), tool("hoa-packet-checklist")]))

    p.append(cs_page("poinciana", "concrete-patios",
        "Concrete Patios in Poinciana, FL – DCB Rules, Screen Rooms",
        "Concrete patios and screen-room slabs in Poinciana: APV Design Control Board approval for any paved area, Solivita's ARC and setbacks, Osceola or Polk permit position, 4-in slabs sloped away from the house, costs.",
        f"A concrete patio in Poinciana runs {cost_range('concrete-patio')} ({R} Cost Index); a 12-by-12 slab lands around $1,300 to $1,900. The APV Design Control Board requires prior written approval for any patio or paved area, and Solivita's ARC reviews patios and screen enclosures separately. A detached slab outside setbacks is generally flatwork in both counties; a slab under a screen room is permitted with the enclosure.",
        [
            ("Patios and screen rooms in the villages", f"<p>Poinciana's 1970s–90s homes were built with a small rear stoop or a 10-by-10 slab; most patio work is extending that slab to 12 by 20 or more, often as the floor of a future screen room. We pour 4 inches of 3,000 psi with fiber on 2 to 4 inches of compacted base, dowel into the existing slab, and slope ⅛ inch per foot away from the house, which on Poinciana's flat lots means a slot drain at the far edge or a swale to the canal side. If a screen enclosure is coming, tell us: the enclosure's footers are its contractor's scope and change the slab edge. Solivita's guidelines list screen enclosures and patio pavers as ARC items and set rear setbacks; the DCB requires approval for any paved area ({hoa('solivita')}, {hoa('poinciana-apv')}).</p>"),
            ("Permits", f"<p>Osceola villages: a detached patio outside setbacks is flatwork without a building permit; a slab within setbacks, attached under a roof or in a flood zone is confirmed with the Building Office (407-742-0200). Polk villages: the county FAQ requires permits for slabs adjacent to a structure and intended to support one, within setbacks, or elevated, so a screen-room slab is permitted with the enclosure and a detached patio outside setbacks is not; Polk Building Division 863-534-6080. HB 803's $7,500 exemption can apply to a stand-alone patio with a written request. Pages: {juris('osceola-county')}, {juris('polk-county')}, {tool('permit-finder')}.</p>"),
        ],
        ("A Village 5 lanai extension", f"<p>Existing 10-by-12 slab extended to 12 by 24 (168 square feet added), doweled, broom finish, slot drain at the outer edge. At {cost_range('concrete-patio')} with a small-pour premium: $1,500 to $2,100. DCB approval, two days on site. Ranges from the {R} index.</p>"),
        ("Does a backyard patio need DCB approval in Poinciana?", "Yes. The criteria say no patio, paved area or other structure may be commenced without prior written DCB approval, regardless of whether the county requires a permit. Submit a site plan with the slab dimensions and finish; a plain concrete patio behind the house is routine, but it still needs the letter."),
        [
            faq("Do I need a county permit for a patio slab?", "Usually not for a detached slab outside setbacks in either county; a slab under a screen room is permitted with the enclosure. We confirm for the address."),
            faq("Broom or smooth?", "Broom outdoors; smooth only under a solid roof."),
            faq("Can you extend my existing slab?", "Yes, doweled every 24 inches with an expansion joint at the seam and the new section sloped away from the house."),
            faq("What about Solivita?", "Solivita's own ARC reviews patios, pavers and screen enclosures with the form in its requirements document; the DCB does not apply inside Solivita."),
        ],
        ["apv", "solivita", "osceola-faq", "polk-faq", "hb803"],
        [cs("poinciana", "concrete-driveways"), svc("paver-patios"), compare("stamped-vs-pavers")]))

    p.append(cs_page("poinciana", "concrete-repair",
        "Concrete Repair in Poinciana, FL – Panels, Aprons, Walks",
        "Concrete repair in Poinciana's older villages: stepped garage panels, broken apron corners, walks capped at 2 ft by the DCB, lift vs. replace on 1970s–90s slabs, well-water rust, costs.",
        f"Concrete repair in Poinciana is mostly 1972–1990 driveways in Villages 1 through 6: a stepped panel at the garage, an apron corner broken by delivery trucks, a front walk lifted by a tree. Routing and sealing or grinding is a minimum-charge visit; a replaced panel runs at new-pour rates ({cost_range('concrete-driveway-broom')}) plus removal. The DCB requires approval for driveway work even in the same footprint when it is visible, and the county needs no permit for same-footprint repair.",
        [
            ("Repair or replace on a forty-year-old slab", f"<p>When one panel has stepped and the other three have hairline cracks, the drive is on one clock, and we price the panel and the whole replacement side by side ({cs('poinciana', 'concrete-driveways')}). Lifting with polyurethane makes sense for a sound, newer slab with a small void after the downspout is fixed; on a 1980s panel that carries the car every day, replacement is the better dollar ({compare('resurface-vs-replace')}). Apron corners broken by trucks get replaced at 6 inches with edge steel; walks get ground or a panel replaced, within the DCB's 2-foot width limit for walks beside the house (Criteria 9.1.1). Rust from well irrigation, common on the older villages' lots, is a stain, not a slab defect ({guide('rust-stains-irrigation-well-water')}).</p>"),
            ("Approvals", f"<p>The DCB criteria cover alterations to driveways and paved areas, and owners must keep driveways, walks and patios clean and in repair (9.2.2); a visible panel replacement gets an application because the new concrete is lighter for a year. Same-footprint repair needs no county permit; an apron in the right-of-way is confirmed with the county (Osceola driveway permit, or Polk's right-of-way rule). Pages: {hoa('poinciana-apv')}, {juris('osceola-county')}, {juris('polk-county')}.</p>"),
        ],
        ("A Village 1 apron corner", f"<p>Apron corner broken off by a moving truck on a 1979 drive, rest of the drive cracked but level. Corner section saw-cut (40 square feet), removed, replaced at 6 inches with #4 edge bars, matched to the county apron detail. Removal $80 to $160, new section at $11.50 to $17: $460 to $680. DCB notified, county driveway permit for the right-of-way portion. One day. Ranges from the {R} index.</p>"),
        ("Why does every driveway in my Poinciana village have the same crack?", "Same builder, same decade, same 4-inch slab on sand with no base. The garage-edge step and the apron diagonal are what that construction does after forty wet seasons on Smyrna and Myakka sand. Repairing a panel is fine when the rest is sound; in Villages 1 through 4 the rest usually is not, and the honest quote shows both numbers."),
        [
            faq("Do repairs need DCB approval?", "Visible driveway work does; the criteria cover alterations to paved areas. We submit a short application with the panel location."),
            faq("Can you grind the walk lip?", "Under ¾ inch, yes, same week. Larger lifts get a panel replaced over a root barrier."),
            faq("Is lifting worth it?", "On a sound, newer slab after the water is fixed. Not on a cracked 1980s panel at the garage."),
            faq("Do you fix the rust stains?", "We remove them with an iron-specific cleaner; they return unless the sprinkler heads are adjusted or the well water is filtered."),
        ],
        ["apv", "osceola-22-50-6", "polk-faq"],
        [cs("poinciana", "concrete-driveways"), guide("why-concrete-cracks-osceola"), svc("concrete-resurfacing")]))

    p.append(cs_page("poinciana", "paver-driveways",
        "Paver Driveways in Poinciana, FL – DCB Materials, Polk Release",
        "Paver driveways in Poinciana: brick pavers as an accepted DCB material, approval before any work, Osceola driveway permit or Polk's Paver Release Form, flatwoods vs. ridge base, cost per sq ft.",
        f"A paver driveway in Poinciana runs {cost_range('paver-driveway-concrete')} ({R} Cost Index) plus $2 to $4 per square foot to remove the old concrete. The APV Design Control Board lists brick pavers among accepted driveway materials and requires written approval before work starts; on the Osceola side the county driveway permit applies, and on the Polk side pavers that reach the right-of-way need a recorded Paver Release Form. Solivita reviews paver conversions through its own ARC.",
        [
            ("Pavers in the villages", f"<p>Most Poinciana driveways are concrete and most replacements stay concrete, but owners in Villages 7 through 9 and along the Poinciana Parkway side increasingly choose pavers for the look and because a sunken area can be lifted later. Our section is the standard 6 inches of compacted limerock, 1 inch of bedding sand, 80 mm pavers, restraint on the base and polymeric sand; on the Osceola villages' Smyrna and Myakka sand the subgrade is proof-rolled and drained, on the western villages' Candler sand it is wetted before compaction ({guide('paver-base-flatwoods-vs-ridge')}). The apron in the right-of-way is concrete in most cases, with a soldier course at the seam.</p>"),
            ("DCB, Solivita, and two counties", f"<p>DCB application first: material, color, pattern, site plan, at 401 Walnut Street (863-427-0900); 30 days of silence is a denial. Solivita residents use the Solivita ARC, which requires replacement driveways in the original builder's style and materials and reviews extensions and modifications, so a concrete-to-paver conversion there is a case-by-case request with a sample. County: Osceola driveway permit under §22-50.6 with the 24-foot limit, or Polk's rules with the notarized, recorded Concrete Driveway Paver Release Form if pavers reach the right-of-way. Pages: {hoa('poinciana-apv')}, {hoa('solivita')}, {juris('osceola-county')}, {juris('polk-county')}, {tool('permit-finder')}.</p>"),
        ],
        ("A Village 7 concrete-to-paver conversion", f"<p>440-square-foot two-car drive, 2004 concrete cracked, Polk side. DCB approval, Polk right-of-way rule handled with a concrete apron so no release form was needed, removal ($880 to $1,760), 6-inch base on wetted Candler sand, 80 mm pavers in herringbone with a soldier border at $14 to $22 ($6,160 to $9,680), seal at 60 days. Four days. Ranges from the {R} index.</p>"),
        ("Can I have a paver driveway in Solivita?", "Only through the Solivita ARC, and only if it approves a departure from the builder's original material: the requirements say replacement driveways and walkways must be in the same style and material the original builder used, and extensions or modifications are reviewed individually. Some requests are approved with samples; plan on the review before ordering pavers."),
        [
            faq("Are pavers allowed by the DCB?", "Brick pavers are an accepted driveway material under Criteria 9.1.1, with prior written approval."),
            faq("What is the Polk Paver Release Form?", "A notarized, recorded form the county requires when pavers go in its right-of-way; a concrete apron avoids it."),
            faq("Concrete or pavers?", "Concrete costs less and is the DCB default; pavers can be lifted for repair and widened with matching units."),
            faq("How long does it take?", "Three to five days after DCB approval and the county permit."),
        ],
        ["apv", "solivita", "osceola-22-50-6", "polk-paver-release", "sda"],
        [cs("poinciana", "concrete-driveways"), compare("concrete-vs-pavers"), tool("hoa-packet-checklist")]))

    return p
